-- AlterTable
ALTER TABLE "endorsement_transaction" ADD COLUMN     "createDateTime" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "createdBy" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "deletedAt" TIMESTAMP(6),
ADD COLUMN     "lastChangedBy" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "lastChangedDateTime" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "type" TEXT;
