name: "🐛 Bug Report"
description: Report a bug or unexpected behavior in the project
labels: [bug]
title: "fix: "
body:
  - type: checkboxes
    id: agreement
    attributes:
      label: Preliminary Checks
      options:
        - label: I have read the contributions guide [contibution guide](https://docs.credebl.id/docs/contribute/how-to-contribute) and agree to it
          required: true
        - label: I have searched [existing issues](https://github.com/credebl/platform/issues) and [pull requests](https://github.com/credebl/platform/pulls) to avoid duplicates.
          required: true
        - label: "I'm willing to create a PR for this feature. (if applicable)."
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Description

        _A clear and concise description of what the bug is._

        When I try to [...], I get this unexpected behavior [...]

        ---

        ## 🧪 Steps to Reproduce

        _Provide clear steps to reproduce the bug._

        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error

        ---

        ## ✅ Expected Behavior

        _What did you expect to happen?_

        ---

        ## ❌ Actual Behavior

        _What actually happened instead?_

        ---

        ## 📌 Affected Version/Commit

        _Version number, branch name, or commit hash where the bug occurs._

        ---

        ## 💻 Environment

        _Where did the issue occur?_

        - [ ] Local development  
        - [ ] Production  
        - [ ] CI/CD  
        - [ ] Other  

        ---

        ## 🧾 Relevant Logs, Screenshots, or Stack Traces

        _Paste any error messages or screenshots that can help diagnose the issue._
    validations:
      required: false
