name: "🚀 Feature Request"
description: Suggest an idea or enhancement for this project
labels: [enhancement]
title: "feat: "
body:
  - type: checkboxes
    id: agreement
    label: Preliminary Checks
    options:
      - label: "I've read the contributions guide [contibution guide](https://docs.credebl.id/docs/contribute/how-to-contribute) and agree to it"
        required: true
      - label: "I have searched [existing issues](https://github.com/credebl/platform/issues) and [pull requests](https://github.com/credebl/platform/pulls) to avoid duplicates."
        required: true
      - label: "I'm willing to create a PR for this feature. (if applicable)."
  - type: markdown
    attributes:
      value: |
        ## 🧩 Problem Statement

        _Is your feature request related to a problem? Please describe it clearly._

        > Ex: I'm always frustrated when [...]

        ---

        ## 💡 Proposed Solution

        _A clear and concise description of what you want to happen._

        > Ex: It would be great if [...]

        ---

        ## 🔄 Alternatives Considered

        _Have you considered any alternative solutions or features?_

        > Ex: I also thought about [...], but [...]

        ---

        ## 📎 Additional Context

        _Add any other context, references, mockups, or screenshots here._

        ---

        ## ✅ Acceptance Criteria

        _List specific tasks or outcomes that define when this request is complete._

        - A new endpoint `/v1/...` is added  
        - Docs updated  
        - Tests written and passing
    validations:
      required: false
