version: '3'

services:
  agent:
    image: afj-0.4.2:latest

    container_name: agent1_a0630c86-2c26-4677-9000-ede3ed2b4833
    restart: always
    environment:
      AFJ_REST_LOG_LEVEL: 1
    ports:
     - 9001:9001
     - 8001:8001
   
    volumes: 
      - ./agent-config/1_a0630c86-2c26-4677-9000-ede3ed2b4833.json:/config.json   
      
    command: --auto-accept-connections --config /config.json
      
volumes:
  pgdata:
  agent-indy_client:
  agent-tmp:
