version: '3'

services:
  agent:
    image: afj-0.4.2:latest

    container_name: agent1_d6926810-a836-4443-8378-49ba32d8ede3
    restart: always
    environment:
      AFJ_REST_LOG_LEVEL: 1
    ports:
     - 9001:9001
     - 8001:8001
   
    volumes: 
      - ./agent-config/1_d6926810-a836-4443-8378-49ba32d8ede3.json:/config.json   
      
    command: --auto-accept-connections --config /config.json
      
volumes:
  pgdata:
  agent-indy_client:
  agent-tmp:
