version: '3'

services:
  agent:
    image: afj-0.4.2:latest

    container_name: agent1_9cc088d4-4b65-4a2e-a50f-9623d9e701c3
    restart: always
    environment:
      AFJ_REST_LOG_LEVEL: 1
    ports:
     - 9001:9001
     - 8001:8001
   
    volumes: 
      - ./agent-config/1_9cc088d4-4b65-4a2e-a50f-9623d9e701c3.json:/config.json   
      
    command: --auto-accept-connections --config /config.json
      
volumes:
  pgdata:
  agent-indy_client:
  agent-tmp:
