version: '3'

services:
  agent:
    image: afj-0.4.2:latest

    container_name: bcdee08b-a116-4fd4-a431-f117459046bd_Platform-admin
    restart: always
    environment:
      AFJ_REST_LOG_LEVEL: 1
    ports:
     - 9017:9017
     - 8017:8017
   
    volumes: 
      - ./agent-config/bcdee08b-a116-4fd4-a431-f117459046bd_Platform-admin.json:/config.json   
      
    command: --auto-accept-connections --config /config.json
      
volumes:
  pgdata:
  agent-indy_client:
  agent-tmp:
