# Stage 1: Build the application
FROM node:24-alpine3.21 AS build
RUN apk update && apk upgrade && apk add --no-cache \
    openssl \
    openssh-client \
    aws-cli \
    docker \
    docker-compose \
    && rm -rf /var/cache/apk/*
RUN npm install -g pnpm@latest --ignore-scripts
WORKDIR /app
COPY package.json pnpm-workspace.yaml ./
ENV PUPPETEER_SKIP_DOWNLOAD=true
RUN pnpm i --ignore-scripts
COPY . .
RUN cd libs/prisma-service && npx prisma generate
RUN pnpm run build agent-service

# Stage 2: Create the final image
FROM node:24-alpine3.21
RUN apk update && apk upgrade && apk add --no-cache \
    openssl \
    openssh-client \
    aws-cli \
    docker \
    docker-compose \
    && rm -rf /var/cache/apk/* \
    && addgroup -g 1001 -S nodejs \
    && adduser -S nextjs -u 1001
WORKDIR /app
COPY --from=build --chown=nextjs:nodejs /app/dist/apps/agent-service/ ./dist/apps/agent-service/
COPY --from=build --chown=nextjs:nodejs /app/libs/ ./libs/
COPY --from=build --chown=nextjs:nodejs /app/node_modules ./node_modules
USER nextjs
CMD ["sh", "-c", "cd libs/prisma-service && npx prisma migrate deploy && npx prisma generate && cd ../.. && node dist/apps/agent-service/main.js"]
