# Stage 1: Build the application
FROM node:18-alpine as build

RUN npm install -g pnpm --ignore-scripts \
    && apk update \
    && apk add openssh-client \
    && apk add aws-cli \
    && apk add docker \
    && apk add docker-compose 

# Add PostgreSQL client to the image
RUN apk add --no-cache postgresql-client

RUN npm install -g pnpm

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./

# Install dependencies
RUN pnpm i \
    && pnpm add -D ts-node typescript @types/node --ignore-scripts


# Copy the rest of the application code
COPY . .

RUN chown -R node:node /app/libs/prisma-service/prisma/scripts/
RUN chmod +x /app/libs/prisma-service/prisma/scripts/geo_location_data_import.sh
RUN chmod +x /app/libs/prisma-service/prisma/scripts/update_client_credential_data.sh

# RUN cd libs/prisma-service && npx prisma migrate deploy && npx prisma generate
RUN cd libs/prisma-service && npx prisma migrate deploy && npx prisma generate && npx prisma db seed

# Build the user service
RUN pnpm run build agent-service

# Stage 2: Create the final image
FROM node:18-alpine

RUN npm install -g pnpm --ignore-scripts \
    && apk update \
    && apk add openssh-client \
    && apk add aws-cli \
    && apk add docker \
    && apk add docker-compose 

RUN npm install -g pnpm
# Set the working directory
WORKDIR /app

# Copy the compiled code from the build stage
COPY --from=build /app/dist/apps/agent-service/ ./dist/apps/agent-service/

# Copy the libs folder from the build stage
COPY --from=build /app/libs/ ./libs/
#COPY --from=build /app/package.json ./  
COPY --from=build /app/node_modules  ./node_modules

# Set the command to run the microservice
CMD ["sh", "-c", "cd libs/prisma-service && npx prisma migrate deploy && npx prisma db seed && cd ../.. && node dist/apps/agent-service/main.js"]