# Stage 1: Build the application
FROM node:24-alpine3.24@sha256:ebfe2f90462722a7a4de65e91990e97fe0d401c70e0e762c5b53302f905ec1c1 AS build
RUN apk update && apk upgrade && apk add --no-cache openssl && rm -rf /var/cache/apk/*
RUN npm install -g pnpm@9.15.9 --ignore-scripts
WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
ENV PUPPETEER_SKIP_DOWNLOAD=true
RUN pnpm i --frozen-lockfile --ignore-scripts
COPY . .
RUN cd libs/prisma-service && npx prisma generate
RUN pnpm run build notification
RUN pnpm prune --prod

# Stage 2: Create the final image
FROM node:24-alpine3.24@sha256:ebfe2f90462722a7a4de65e91990e97fe0d401c70e0e762c5b53302f905ec1c1
RUN apk update && apk upgrade && apk add --no-cache openssl \
    && rm -rf /var/cache/apk/* \
    && addgroup -g 1001 -S nodejs \
    && adduser -S nextjs -u 1001
WORKDIR /app
COPY --from=build /app/dist/apps/notification/ ./dist/apps/notification/
COPY --from=build /app/libs/ ./libs/
COPY --from=build /app/node_modules ./node_modules
USER nextjs
CMD ["sh", "-c", "cd libs/prisma-service && npx prisma migrate deploy && cd ../.. && node dist/apps/notification/main.js"]