#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commit_msg_file=$1
if ! grep -q "Signed-off-by:" "$commit_msg_file"; then
  echo "Commit message missing Signed-off-by line"
  echo "Use: git commit -s ..."
  exit 1
fi
