name: Utility

on:
  push:
    tags:
      - 'v*'

env:
  SERVICE: utility

jobs:
  build-and-push:
    name: Push Docker image to GitHub
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Git Tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}

      - name: Build and Push Docker Image
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          SERVICE_NAME="${{ env.SERVICE }}"
          IMAGE_TAG="${{ env.TAG }}"

          IMAGE_NAME="ghcr.io/${REPO_OWNER}/${SERVICE_NAME}:${IMAGE_TAG}"
          IMAGE_LATEST="ghcr.io/${REPO_OWNER}/${SERVICE_NAME}:latest"

          echo "Building Docker image for utility ..."
          docker build -t $IMAGE_NAME -f Dockerfiles/Dockerfile.${SERVICE_NAME} .

          docker tag "${IMAGE_NAME}" "${IMAGE_LATEST}"

          echo "Pushing Docker image: ${IMAGE_NAME}"
          docker push "${IMAGE_NAME}"

          echo "Pushing Docker image: ${IMAGE_LATEST}"
          docker push "${IMAGE_LATEST}"